FROM bioconductor/bioconductor_docker:3.21

RUN R -e "install.packages(c('BiocManager', 'remotes'))"

RUN R -e "remotes::install_version(package = 'arrow', version = '21.0.0', upgrade = 'never')"

RUN R -e "BiocManager::install(c('Seurat', 'SeuratObject', 'Signac', 'patchwork', 'data.table', 'dplyr', 'argparse', 'R.utils'), update=FALSE)"
