FROM bioconductor/bioconductor_docker:3.21

RUN R -e "install.packages('BiocManager')"

RUN R -e "BiocManager::install(c('Seurat', 'SeuratObject', 'Signac', 'patchwork', 'data.table', 'dplyr', 'argparse', 'R.utils'), update=FALSE)"
