- name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: envs/
          file: envs/Dockerfile.seurat
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_IMAGE }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_IMAGE }}:${{ github.sha }}
          secrets: |
            gh_token=${{ secrets.GH_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max